version: '3.9'
services:

  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:6.2.2-php8.1-fpm # Wordpress PHP8.1
    # image: wordpress:6.2.2-php8.2-fpm # Wordpress PHP8.2
    container_name: wp-wordpress
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      - ${WORDPRESS_LOCAL_PLUGINS}:/var/www/html/wp-content/plugins/
      - ${WORDPRESS_LOCAL_THEMES}:/var/www/html/wp-content/themes/
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  # Redis
  redis:
    # image: redis:7.0.12 # Official Redis image
    image: rapidfort/redis:7.0.11 # Alternative RapidFort hardened image
    container_name: wp-redis
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ${REDIS_DATA}:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - wordpress
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  # Database MySQL
  database:
    # image: bitnami/mysql:8.0.34 # Alternative Bitnami image
    # image: mysql:8.0.33 # Official MySQL image
    image: rapidfort/mysql:8.0.33 # Alternative RapidFort hardened image
    container_name: wp-database
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    ports:
      - '3306:3306'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_AUTHENTICATION_PLUGIN=CACHING_SHA2_PASSWORD
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=CACHING_SHA2_PASSWORD
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    #  - ${MYSQL_LOCAL_HOME}:/var/lib/mysql # Original image
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:alpine
    # image: rapidfort/nginx:1.2.4 # Alternative RapidFort hardened image
    container_name: wp-nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "80:80"    # http
      - "443:443"   # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

  filebrowser:
    image: hurlenko/filebrowser
    container_name: wp-filebrowser
    env_file:
      - .env
    user: "0:0" # Put in your UID:GID
    ports:
      - "8080:8080"
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/data
      - ${FILEBROWSER_CONFIG}:/config
    environment:
      - FB_USERNAME=fileadm23 # Username is 'fileadm23'. Please change the username upon login
      - FB_PASSWORD=$$2y$$08$$pjAWcSAz7CLNUVntdt2UMOUxjCq7quPOMwb3pGjfRt1aPdi7stkP6 # Password is 'FileChangeMe23Browser'. Please change the password upon login
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  # To run filebrowser behind Nginx, please refer https://hub.docker.com/r/hurlenko/filebrowser
  # You can use the script htpasswd -bnBC 8 "" FileChangeMe23Browser | grep -oP '\$2[ayb]\$.{56}' to get hashed password.

  # adminer - bring up only as needed - bypasses nginx
  # adminer:
  #  # default port 8080
  #   image: adminer:4
  #   container_name: wp-adminer
  #   restart: unless-stopped
  #   networks:
  #     - wordpress
  #   depends_on:
  #     - database
  #   ports:
  #     - "9999:8080"

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge

volumes:
  mysql_data:
    driver: local